source = $HOME/.config/hypr/modules/monitors.conf
source = $HOME/.config/hypr/modules/autostart.conf
source = $HOME/.config/hypr/modules/envs.conf
source = $HOME/.config/hypr/modules/devices.conf
source = $HOME/.config/hypr/modules/looknfeel.conf
source = $HOME/.config/hypr/modules/bindings/apps.conf
source = $HOME/.config/hypr/modules/bindings/tiling.conf
source = $HOME/.config/hypr/modules/bindings/media.conf
source = $HOME/.config/hypr/modules/bindings/utilities.conf
source = $HOME/.config/hypr/modules/bindings/clipboard.conf
source = $HOME/.config/hypr/modules/windows.conf

plugin {
    split-monitor-workspaces {
        count = 3
        enable_persistent_workspaces = true
        enable_wrapping = true
    }
}
