input {
    kb_options = caps:swapescape, compose:ralt
    accel_profile = flat
    sensitivity = 0
    scroll_factor = 1
}

device {
    name = elan06d4:00-04f3:32b5-touchpad
    sensitivity = 1
}

gesture = 3, horizontal, workspace
