monitor = eDP-1, preferred, 0x0, 1
monitor = desc:S24F350, 1920x1080@60, 1920x0, 1
monitor = desc:F24G3xTF, 1920x1080@60, 3840x0, 1

# handle lid open/close, migrate windows off eDP-1 before disabling
bindl = , switch:on:Lid Switch, exec, lid-handler close
bindl = , switch:off:Lid Switch, exec, lid-handler open
exec = lid-handler
