# ignore maximize requests
windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

# fix dragging issues with xwayland
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# centre floating popup/dialog windows
windowrule {
    name = center-dialogs
    match:float = true

    center = 1
}

# bitwarden floating panel
windowrule {
    name = bitwarden-float
    match:class = Bitwarden

    float = true
    size = 500 700
    center = 1
}

# mullvad vpn in scratchpad
windowrule {
    name = mullvad-scratchpad
    match:class = Mullvad VPN

    float = true
    workspace = special:magic
    center = 1
}

# float tui apps
windowrule {
    name = floating-tui
    match:title = ^(wiremix|bluetui|impala|btop)$

    float = true
    size = 900 600
    center = 1
}

# pin webcam overlay to bottom-right corner
windowrule {
    name = webcam-overlay
    match:title = WebcamOverlay

    float = true
    pin = true
    move = (monitor_w-window_w-20) (monitor_h-window_h-20)
    size = 480 270
}
